apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-deployment
  namespace: nagp-assignment
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: springboot-crud-k8s
          image: manmeetdevgun/booking-service:latest
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables

            - name: DATABASE_SERVER  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : booking-service-config
                  key :  DATABASE_SERVER
                  
            - name: DATABASE_USERNAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : booking-service-config
                  key :  DATABASE_USERNAME

            - name: DATABASE_PASSWORD  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : booking-service-secret
                  key :  DATABASE_PASSWORD

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-crud-svc
  namespace: nagp-assignment
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.
