apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: booking-service-db
  name: booking-service-db
  namespace: nagp-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service-db
  template:
    metadata:
      labels:
        app: booking-service-db
    spec:
      containers:
      - image: mysql:5.6
        name: booking-service-db
        ports:
        - containerPort: 3306
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: booking-service-secret
              key: DATABASE_PASSWORD
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-azuredisk
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service-db
  namespace: nagp-assignment
spec:
  ports:
  - port: 3306
  selector:
    app: booking-service-db