apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: nagp-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        ports:
        - containerPort: 3306
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: booking-service-secret
              key: DATABASE_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: booking-service-secret
              key: DATABASE_PASSWORD
              
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: nagp-assignment
  labels:
    app: mysql
    tier: database
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
    tier: database