apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: nagp-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: booking-service
        image: manmeetdevgun/booking-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
           name: booking-service-config
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: booking-service-secret
              key: DATABASE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  labels:
    bb: web
    name: booking-service
  name: booking-service
  namespace: nagp-assignment
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080