apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk
  namespace: nagp-assignment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-csi-premium